### ISSUE TITLE
[Quenstion] build_operation_graph failed

### ISSUE THREAD

**Issue by zhewenhu** [NVIDIA/cudnn-frontend#104]
Hello all,

I'm attempting to create a graph with two consecutive **conv_fprop** operations, but I'm encountering an error when calling **build_operation_graph()**. The error message is:
`CUDNN_BACKEND_TENSOR_DESCRIPTOR: SetAttribute CUDNN_ATTR_TENSOR_DATA_TYPE Failed cudnn_status: CUDNN_STATUS_INVALID_VALUE`

I'm new to cuDNN and am having trouble identifying the cause of the issue. Could anyone provide some guidance on how to debug this? Below is my code:

```
        int64_t n = 1; 
        int64_t c = 1;
        int64_t h = 64, w = 64; 
        int64_t k = 1;
        int64_t r = 3, s = 3; 

        graph = std::make_shared<fe::graph::Graph>();
        graph->set_io_data_type(fe::DataType_t::FLOAT).set_compute_data_type(fe::DataType_t::FLOAT);

        auto conv_options =
            fe::graph::Conv_fprop_attributes().set_padding({0, 0}).set_stride({1, 1}).set_dilation({1, 1});

        X = graph->tensor(fe::graph::Tensor_attributes()
                              .set_name("input")
                              .set_dim({n, c, h, w})
                              .set_stride({c * h * w, 1, c * w, c})
                              .set_data_type(fe::DataType_t::FLOAT));

        W1 = graph->tensor(fe::graph::Tensor_attributes()
                               .set_name("weight1")
                               .set_dim({k, c, r, s})
                               .set_stride({c * r * s, 1, c * s, c})
                               .set_data_type(fe::DataType_t::FLOAT));

        Y1 = graph->conv_fprop(X, W1, conv_options);

        W2 = graph->tensor(fe::graph::Tensor_attributes()
                               .set_name("weight2")
                               .set_dim({k, c, r, s})
                               .set_stride({c * r * s, 1, c * s, c})
                               .set_data_type(fe::DataType_t::FLOAT));

        Y2 = graph->conv_fprop(Y1, W2, conv_options);

        Y2->set_output(true).set_data_type(fe::DataType_t::FLOAT);

        checkCudnnFeErr(graph->validate(), "Graph validation failed");
        checkCudnnFeErr(graph->build_operation_graph(handle), "Building operation graph failed");
        checkCudnnFeErr(graph->create_execution_plans({fe::HeurMode_t::A}), "Creating execution plans failed");
        checkCudnnFeErr(graph->check_support(handle), "Checking graph support failed");
        checkCudnnFeErr(graph->build_plans(handle), "Building plans failed");
```

**Comment by vedaanta** [comment]
The data type for Y1 is not set.

Y1 is not an input or an output. So the following line did not set Y1's data type:
`graph->set_io_data_type(fe::DataType_t::FLOAT).set_compute_data_type(fe::DataType_t::FLOAT);`

You can either set graph level intermediate tensor data type:
`graph->set_intermediate_data_type(fe::DataType_t::FLOAT);`
OR just set Y1 data type explicitly:
`Y1->set_data_type(fe::DataType_t::FLOAT);`


------
(Also, I dont think the graph you are running is supported by cudnn today? Its a fused conv-conv graph.)

**Comment by zhewenhu** [comment]
Thank you @vedaanta , it solves my problem, and indeed the graph is not supported. Am I only able to create the graphs listed in [Graph API](https://docs.nvidia.com/deeplearning/cudnn/latest/developer/graph-api.html#id24)?

**Comment by vedaanta** [comment]
Yes, you will only find support for graphs listed in the documentation.

Is there a specific usecase/model/graph you are looking at? If so, I can help see what graph patterns you can use from cudnn.

**Comment by zhewenhu** [comment]
> Yes, you will only find support for graphs listed in the documentation.
> 
> Is there a specific usecase/model/graph you are looking at? If so, I can help see what graph patterns you can use from cudnn.

Yes, I am implementing a UNet model. You can find the PyTorch version [here](https://github.com/Project-MONAI/MONAI/blob/59a7211070538586369afd4a01eca0a7fe2e742e/monai/networks/nets/basic_unet.py#L178-L279). Thank you very much for the help!

**Comment by zhewenhu** [comment]
Hi @vedaanta , is there any graph I can use to build the [UpCat](https://github.com/Project-MONAI/MONAI/blob/59a7211070538586369afd4a01eca0a7fe2e742e/monai/networks/nets/basic_unet.py#L92) layer in the UNet? Seems upsampling is not supported with a layout of NCHW?

**Comment by Anerudhan** [comment]
There is a limitation each sub-graph can have only one convolution and you need to partition you Graph class into sub-graphs. The supported graph formats are documented [here](https://docs.nvidia.com/deeplearning/cudnn/latest/developer/graph-api.html#supported-graph-patterns)

**Comment by mazispider** [comment]
I am using convolution and relu in the same graph, but create_execution_plans returns false. I have been getting getting my hands on cudnn frontend. I'd be happy if someone could help me with the code below:

`int64_t n = 256, c = 3, h = 224, w = 224, k = 32, r = 5, s = 5;

auto build_new_graph = [=](cudnnHandle_t handle) {
    auto graph = std::make_shared<fe::graph::Graph>();
    graph->set_io_data_type(fe::DataType_t::FLOAT).set_compute_data_type(fe::DataType_t::FLOAT).set_intermediate_data_type(fe::DataType_t::FLOAT);
    auto X = graph->tensor(fe::graph::Tensor_attributes()
                               .set_name("image")
                               .set_dim({n, c, h, w})
                               .set_stride({c * h * w, h * w, w, 1}));
    auto W = graph->tensor(fe::graph::Tensor_attributes()
                               .set_name("filter")
                               .set_dim({k, c, r, s})
                               .set_stride({c * r * s, r * s, s, 1}));
    auto conv_options =
        fe::graph::Conv_fprop_attributes().set_padding({0, 0}).set_stride({1, 1}).set_dilation({1, 1});
    auto Y1 = graph->conv_fprop(X, W, conv_options);
    
    Y1->set_data_type(fe::DataType_t::FLOAT);
    auto relu_options = fe::graph::Pointwise_attributes().set_mode(fe::PointwiseMode_t::RELU_FWD).set_compute_data_type(fe::DataType_t::FLOAT);
    auto Y = graph->pointwise(Y1, relu_options);
    
    Y->set_data_type(fe::DataType_t::FLOAT).set_output(true);
    CHECK(graph->validate().is_good());
    CHECK(graph->build_operation_graph(handle).is_good());
    CHECK(graph->create_execution_plans({fe::HeurMode_t::A}).is_good());
    CHECK(graph->check_support(handle).is_good());
    CHECK(graph->build_plans(handle).is_good());
    return std::make_tuple(graph, X, W, Y);
};`

**Comment by Anerudhan** [comment]
Hi @mazispider ,

Thanks for the query. NHWC is the preferred layout for flexible fusions in cuDNN.

Modifying the above sample to

```
        auto X = graph->tensor(fe::graph::Tensor_attributes()
                                   .set_name("image")
                                   .set_dim({n, c, h, w})
                                   .set_stride({c * h * w, 1, c * w, c}));

        auto W = graph->tensor(fe::graph::Tensor_attributes()
                                   .set_name("filter")
                                   .set_dim({k, c, r, s})
                                   .set_stride({c * r * s, 1, c * s, c}));
```

makes the sample pass. 

Can you also point me to which cudnn version and architecture you are trying this on?

**Comment by mazispider** [comment]
Now it throws the "No valid engine configs for ConvFwd_RELU_FWD_" error. 
CUDA_VERSION = 12.4.1
CUDNN_VERSION = 9.1
GPU_COMOUTE_CAPABILITY = 6.1
