### ISSUE TITLE
Error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by akineeic** [NVIDIA/cudnn-frontend#12]
Hi,

I’m currently using CUDNN to write a deep learning super-resolution sample. But the function `cudnnConvolutionBiasActivationForward` will return status `CUDNN_STATUS_EXECUTION_FAILED`. I check out the API Reference DOC and only find the description "The function failed to launch on the GPU." for this state.

I also found a [similar post](https://forums.developer.nvidia.com/t/debugging-a-cudnnconvolutionforward-cudnn-status-execution-failed/47423) in the NVIDIA forum, but there is no reply in this post. I found that the memory occupied by the graphics card will rise rapidly when running the sample. But I can't debug without specific diagnostic information. Could you give any suggestions for this issue?

Thanks a lot in advance!

**Comment by Anerudhan** [comment]
Hi,


Thanks for filing this issue. Can you please mention which GPU you are
using? Also, it would be great if you attach cuDNN API logs. It will help
us better diagonise the problem.

Thanks

**Comment by YangXu1990uiuc** [comment]
FYI, the steps to enable API logging are described in this doc
https://docs.nvidia.com/deeplearning/cudnn/developer-guide/index.html#api-logging

**Comment by akineeic** [comment]
Thanks for your quick reply! I'm using 2080Ti and cudnn 8.2.1. The environment should be no problem since I can run mnist sample on it. I'll try to enable API logging according to the guide.

**Comment by akineeic** [comment]
This is the API logging output file([log.txt](https://github.com/NVIDIA/cudnn-frontend/files/7502016/log.txt)), could you please take a look and give me some suggestions, thanks!

**Comment by YangXu1990uiuc** [comment]
Thank you akineeic for uploading the sample!
We also recommend trying out the latest cuDNN 8.3.0 at https://developer.nvidia.com/cudnn
If the issue persists with 8.3.0, we will file a bug internally for investigation

**Comment by Anerudhan** [comment]
Hi @akineeic , we see all the test cases in log.txt seem to be passing with cudnn 8.3.0. So, we suggest you upgrade to the latest cudnn version.

Thank you!!

**Comment by akineeic** [comment]
Thanks for your help! I have solved this problem by specifying device 0 to execute the CUDA kernel function. But I don’t know the root cause. I guess it may be that some CUDNN APIs will use device 0 to execute by default when the device is not specified. I will do further testing when I have time.

**Comment by YangXu1990uiuc** [comment]
Hi @akineeic , cuDNN handle is associated to the the cuda device that you choose when you call cudnnCreate. So be sure to use cudaSetDevice to point to the GPU you want to use before calling cudnnCreate.
You can refer to the explanations here. 
https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1g159587909ffa0791bbe4b40187a4c6bb
https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnCreate

Since your issue has been resolved, I'll close this ticket for now. If you find additional issues, feel free to reopen!
